### ISSUE TITLE
Branch - spi-cape support

### ISSUE THREAD

**Issue by RGB-123** [Yona-Appletree/LEDscape#33]
I am getting this error when doing a clean make after checking out this branch.  Maybe some files are missing?

```
  - Building permutation for mapping original-ledscape
    - Generating mapping headers...

module.js:340
    throw err;
          ^
Error: Cannot find module 'strip-json-comments'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/LEDscape/pru/pinmap.js:1:87)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
make: *** [pru/generated/apa102.template] Error 255
```

This results in this error when trying to run opc-server
```

root@beaglebone:~/LEDscape# ./opc-server --mapping rgb-123-v4
main:706: ERROR: Configuration failed validation:
{
        "errors": [
                "Invalid mapping and/or mode name; cannot access PRU 0 program 'pru/bin/ws281x-rgb-123-v4-pru0.bin'",
                "Invalid mapping and/or mode name; cannot access PRU 1 program 'pru/bin/ws281x-rgb-123-v4-pru1.bin'"
        ],
        "valid": false
```

**Comment by RGB-123** [comment]
Yona, the latest commit you pushed compiles and runs.  I'll test on more than one output port later today.  Thanks again!
